# Generated by Django 5.2.5 on 2025-10-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='admin_panel.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=True, help_text='Whether this user account is active'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, help_text='Last login timestamp', null=True),
        ),
    ]
