# Generated by Django 5.2.5 on 2025-10-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('default_currency', models.CharField(default='USD', help_text='Default currency code for the company (e.g., USD, EUR, GBP)', max_length=3)),
                ('country', models.CharField(blank=True, help_text="Company's country", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the approval workflow', max_length=200)),
                ('workflow_type', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('CONDITIONAL', 'Conditional')], default='SEQUENTIAL', help_text='Type of approval workflow', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the workflow')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is active')),
                ('minimum_approval_percentage', models.IntegerField(default=50, help_text='Minimum percentage of approvers required for approval')),
                ('manager_approval_required', models.BooleanField(default=True, help_text='Whether manager approval is required first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this workflow belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='admin_panel.company')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('SPECIFIC_APPROVER', 'Specific Approver'), ('HYBRID', 'Hybrid')], help_text='Type of conditional rule', max_length=20)),
                ('percentage_threshold', models.IntegerField(blank=True, help_text='Percentage threshold for approval (if applicable)', null=True)),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Amount threshold that triggers this rule', max_digits=10, null=True)),
                ('condition_description', models.TextField(blank=True, help_text='Description of the condition')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specific_approver', models.ForeignKey(blank=True, help_text='Specific approver for this rule (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Workflow this rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='admin_panel.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Conditional Rule',
                'verbose_name_plural': 'Conditional Rules',
                'ordering': ['workflow', 'amount_threshold'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Order of this step in the workflow')),
                ('approver_role', models.CharField(choices=[('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], help_text='Role required for this approval step', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this step is required for approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Specific user who can approve at this step', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Workflow this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='admin_panel.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['workflow', 'step_number'],
                'unique_together': {('workflow', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='UserApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description of this rule')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Workflow to use for this user', on_delete=django.db.models.deletion.CASCADE, related_name='user_rules', to='admin_panel.approvalworkflow')),
            ],
            options={
                'verbose_name': 'User Approval Rule',
                'verbose_name_plural': 'User Approval Rules',
                'unique_together': {('user', 'workflow')},
            },
        ),
    ]
