# Generated by Django 5.2.5 on 2025-10-04 10:50

import django.core.validators
import django.db.models.deletion
import employees.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation'), ('MEALS', 'Meals & Entertainment'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('SOFTWARE', 'Software & Subscriptions'), ('TRAINING', 'Training & Education'), ('COMMUNICATION', 'Communication'), ('TRANSPORTATION', 'Transportation'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], help_text='Expense category', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('expense_date', models.DateField(help_text='Date when the expense was incurred')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the expense', max_length=10)),
                ('receipt', models.FileField(blank=True, help_text='Receipt or proof of expense', null=True, upload_to=employees.models.expense_receipt_path)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date when the expense was approved/rejected', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from the approver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager or admin who approved/rejected this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee who submitted this expense', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
