# Generated by Django 5.2.5 on 2025-10-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this expense belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='admin_panel.company'),
        ),
    ]
